---
deployment:
  tasks:
    - export DEPLOYPATH=/home/czdjuaxk/server.neogrid.in

    # Go to project directory
    - /bin/cd $DEPLOYPATH

    # Activate virtual environment
    - source /home/czdjuaxk/virtualenv/server.neogrid.in/3.12/bin/activate

    # Install/update dependencies
    - pip install -r requirements.txt

    # Collect static files
    - python manage.py collectstatic --noinput

    # Apply database migrations
    - python manage.py migrate --noinput

    # Restart Passenger application
    - touch /home/czdjuaxk/server.neogrid.in/tmp/restart.txt