# Generated by Django 6.0.1 on 2026-06-23 05:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_productdepartment_productfamily_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_spec',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
