# Generated by Django 6.0.1 on 2026-06-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_product_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfamily',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productfamily',
            name='image',
        ),
    ]
