# Generated by Django 6.0.1 on 2026-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_remove_productfamily_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdepartment',
            name='slug',
            field=models.SlugField(default=1, help_text='auto generate on save', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfamily',
            name='slug',
            field=models.SlugField(default=2, help_text='auto generate on save', unique=True),
            preserve_default=False,
        ),
    ]
