# Generated by Django 6.0.1 on 2026-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_productdepartment_slug_productfamily_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdepartment',
            name='slug',
            field=models.SlugField(blank=True, help_text='auto generate on save', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='slug',
            field=models.SlugField(blank=True, help_text='auto generate on save', null=True, unique=True),
        ),
    ]
