# Generated by Django 6.0.1 on 2026-06-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_productdepartment_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfamily',
            name='slug',
        ),
    ]
