# Generated by Django 6.0.1 on 2026-06-26 06:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_useraddress_usercartmodel_usercartitemmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warrenty_info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
