# Generated by Django 6.0.1 on 2026-06-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_product_warrenty_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdepartment',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdepartment',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the product department, not mandatory', null=True, upload_to='images/products/department'),
        ),
    ]
