# Generated by Django 6.0.1 on 2026-06-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_productdepartment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the product department, not mandatory', null=True, upload_to='images/products/family'),
        ),
    ]
