# Generated by Django 6.0.1 on 2026-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
