# Generated by Django 6.0.1 on 2026-06-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_project_projectimages_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Application.project'),
            preserve_default=False,
        ),
    ]
