# Generated by Django 6.0.1 on 2026-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_gallery_created_at_gallery_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/images/'),
        ),
    ]
