# Generated by Django 6.0.1 on 2026-07-02 09:05

import Application.UserServices.user_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordermodel',
            name='order_id',
            field=models.CharField(default=Application.UserServices.user_utils.create_order_id, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='unique_id',
            field=models.CharField(default=Application.UserServices.user_utils.create_user_address_id, editable=False, max_length=100, unique=True),
        ),
    ]
