# Generated by Django 6.0.1 on 2026-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_userordermodel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordermodel',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
