# Generated by Django 6.0.1 on 2026-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_userordermodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_chanrge',
            field=models.DecimalField(blank=True, decimal_places=2, default=800, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
