# Generated by Django 6.0.1 on 2026-07-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0022_product_shipping_chanrge_alter_userordermodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_chanrge',
            new_name='shipping_charge',
        ),
    ]
