# Generated by Django 6.0.1 on 2026-07-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_rename_shipping_chanrge_product_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
