# Generated by Django 6.0.1 on 2026-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0024_alter_userordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordermodel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
