# Generated by Django 6.0.1 on 2026-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0025_userordermodel_tracking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
    ]
