# Generated by Django 6.0.1 on 2026-07-07 09:10

import Application.DealerServices.dealer_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0028_alter_userordermodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=Application.DealerServices.dealer_models.create_dealer_id, max_length=10, unique=True)),
                ('dealer_type', models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('SHOWROOM', 'Showroom'), ('SERVICE_CENTER', 'Service Center'), ('OUTLET', 'Outlet')], default='SHOWROOM', max_length=200)),
                ('dealer_name', models.CharField(max_length=200)),
                ('dealer_description', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_email', models.CharField(max_length=200)),
                ('dealer_phone', models.CharField(max_length=200)),
                ('dealer_website', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_address', models.CharField(max_length=200)),
                ('dealer_city', models.CharField(max_length=200)),
                ('dealer_state', models.CharField(max_length=200)),
                ('dealer_pincode', models.CharField(max_length=200)),
                ('dealer_country', models.CharField(default='India', max_length=200)),
                ('dealer_location_iframe', models.TextField(help_text='Copy and paste the google map iframe code here')),
                ('dealer_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('dealer_created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
