# Generated by Django 6.0.1 on 2026-07-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0029_dealers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealers',
        ),
    ]
