# Generated by Django 6.0.1 on 2026-07-08 05:43

import Application.DealerServices.dealer_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0030_delete_dealers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=Application.DealerServices.dealer_models.create_dealer_id, max_length=10, unique=True)),
                ('dealer_type', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_name', models.CharField(max_length=200)),
                ('dealer_description', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_email', models.CharField(max_length=200)),
                ('dealer_phone', models.CharField(max_length=200)),
                ('dealer_website', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_address', models.CharField(max_length=200)),
                ('dealer_city', models.CharField(max_length=200)),
                ('dealer_state', models.CharField(max_length=200)),
                ('dealer_pincode', models.CharField(max_length=200)),
                ('dealer_country', models.CharField(default='India', max_length=200)),
                ('dealer_location_iframe', models.TextField(help_text='Copy and paste the google map iframe code here')),
                ('dealer_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='PENDING', max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('dealer_created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.country')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.state')),
            ],
        ),
    ]
