# Generated by Django 6.0.1 on 2026-07-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0031_country_dealers_state_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.district'),
        ),
    ]
