# Generated by Django 6.0.1 on 2026-07-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0032_dealers_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '1. Country', 'verbose_name_plural': '1. Countries'},
        ),
        migrations.AlterModelOptions(
            name='dealers',
            options={'verbose_name': '4. Dealer', 'verbose_name_plural': '4. Dealers'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': '3. District', 'verbose_name_plural': '3. Districts'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': '2. State', 'verbose_name_plural': '2. States'},
        ),
        migrations.CreateModel(
            name='WarrentyRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100)),
                ('purchased_date', models.DateField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.dealers')),
            ],
        ),
    ]
