# Generated by Django 6.0.1 on 2026-07-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0033_alter_country_options_alter_dealers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrentyregistermodel',
            name='dealer',
        ),
        migrations.DeleteModel(
            name='Dealers',
        ),
        migrations.DeleteModel(
            name='WarrentyRegisterModel',
        ),
    ]
