# Generated by Django 6.0.1 on 2026-07-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0035_warrentyregistermodel_mainfranchasemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarrentyRegisterModel',
            new_name='WarrantyRegisterModel',
        ),
    ]
