# Generated by Django 6.0.1 on 2026-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0037_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='eg: 1 year, 6 month  (full small letters)', max_length=100, null=True),
        ),
    ]
