# Generated by Django 6.0.1 on 2026-07-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0038_product_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
