# Generated by Django 6.0.1 on 2026-07-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0040_phonenumbers_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumbers',
            options={'verbose_name': 'Phone Number', 'verbose_name_plural': 'Phone Numbers'},
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Application.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='Application.country'),
        ),
    ]
